version: '3.3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sibo_backend
    volumes:
      - ./:/var/www/html
    networks:
      - laravel

  webserver:
    image: nginx:alpine
    container_name: laravel_server
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel

 # db:
 #   image: mysql:8.0
 #   container_name: laravel_db
 #   environment:
 #     MYSQL_ROOT_PASSWORD: root
 #     MYSQL_DATABASE: laravel
 #     MYSQL_USER: laraveluser
 #     MYSQL_PASSWORD: laravelpass
 #   ports:
 #     - "3306:3306"
 #   volumes:
 #     - dbdata:/var/lib/mysql
 #   networks:
 #     - laravel

volumes:
  dbdata:

networks:
  laravel:
